import type { NotesCatalog } from "@/types/notes";

// Single source of truth for all notes.
// Extracted from legacy NoteGenix HTML/JS pages.
export const notesCatalog: NotesCatalog = {
  years: [
    {
      slug: "first-year",
      title: "First Year",
      legacyPath: "/HTML/firstyear.html",
      semesters: [
        {
          slug: "sem-1",
          title: "Semester 1",
          legacyPath: "/HTML/fysem1.html",
          subjects: [
            {
              slug: "python",
              title: "Introduction to Programming with Python",
              legacyPath: "/HTML/NotesComponentSem1/python.html",
              notes: [
                { title: "Part 1", fileId: "1DWS1EwTUvM_PnwflC1ocuHzxM-vtJ18X", type: "pdf" },
                { title: "Part 2", fileId: "1DP-xd4Xbee7JsKOhLYrk4HqQED8shawv", type: "pdf" },
                { title: "Part 3", fileId: "1D1diBdASc3Xx8nIfRB7ZBlLrI_VJCHas", type: "pdf" },
                { title: "Part 4", fileId: "1CdCG_NiwCRM6sd8Qn243FBkD35oVpKdX", type: "pdf" },
                { title: "Part 5", fileId: "1Cvc-JGQ1HcgYhTSwuQbNlOkSStxQ530I", type: "pdf" },
                { title: "Python basics 1", fileId: "1CoRkmIKAYUxvuSSJpukIJXKbUsosspxI", type: "pdf" },
                { title: "Python basics 2", fileId: "1DF96Vc29fJUncvGGJLQT0vJMliI0zORP", type: "pdf" },
                { title: "Python PPT", fileId: "1D3aVCPyzsllH1ckUnBsuDBGr7US6IjfX", type: "pdf" },
                { title: "Python Problem Solving", fileId: "1Dvg2XrhfiCwB2GMLpK6oKB1y6QRA0DIp", type: "pdf" },
                { title: "Exception Handling", fileId: "1DuW0CprUgupaEawpWNwx4PUJas8VYgX1", type: "pdf" },
                { title: "File Handling", fileId: "1DqchkONCciF2hHErenVcea__421e15Rd", type: "pdf" },
                { title: "Function", fileId: "1DejRJvNF10kcUSnbsOJ-vK0jkCSVm3w0", type: "pdf" },
                { title: "Module", fileId: "1DaKG9CSo05wHB8IrBx1VsVf53y5SmT01", type: "pdf" },
              ],
            },
            {
              slug: "fcpt",
              title: "Fundamentals of Computers and PC Tools",
              legacyPath: "/HTML/NotesComponentSem1/fcpt.html",
              notes: [
                { title: "Lec 1", fileId: "13X69osEPe-DASTuMB8DpgPE_lqfP2MRt", type: "slides" },
                { title: "Lec 2", fileId: "13UqkeFXFMSfqPCBO1xi3gBggV5j329o_", type: "slides" },
                { title: "Lec 3", fileId: "138OFBBpiNFF6NqUJcLuiZFY91ynefHe7", type: "slides" },
                { title: "Lec 4", fileId: "13LKCJT7wkmjElkTxiBIVHUm6TKrPGJ3K", type: "slides" },
                { title: "Lec 5", fileId: "13jxB7SJnA2mLkpeB1zjrpJ77kfRaZgrR", type: "slides" },
                { title: "Lec 6", fileId: "13iyOOGD0ZXWNal7gdC_8aEY53c8GAhPV", type: "slides" },
                { title: "Lec 7", fileId: "13cBu7zAvK_cUw_olmIZ6j42epYSqYl8l", type: "slides" },
                { title: "Lec 8", fileId: "14N7_E9v3iOAbFgsUq3S0w4YtpD1EDIDp", type: "slides" },
                { title: "Lec 9", fileId: "1tIKTn0Rqh50qcH5KV4g8MukZIJnnYsgO", type: "slides" },
                { title: "Lec 10", fileId: "1JbjaCb_I0UWo3a__SIYdgmZBTUUxW-lH", type: "slides" },
                { title: "Lec 11", fileId: "1oPZEUqDNhitqk-UR2JmyaGOP64QxsoXY", type: "slides" },
                { title: "Resgisters", fileId: "13ZaURQNXw1l108IiofhNQTp14o9w9XJx", type: "slides" },
                { title: "Assignment 1", fileId: "1FzMmb_lS0KGViRFEYCTn2PMorgHdoKF8", type: "pdf" },
                { title: "Assignment 1 Sols", fileId: "1G1Z8US21SaVXI8M_ZQtjw2D1Seb2Sglb", type: "pdf" },
                { title: "Assignment 2", fileId: "1G4WQksKIh8Z6ZhMLfCrvDOpWnWgbV0hc", type: "pdf" },
              ],
            },
            {
              slug: "tc",
              title: "Essentials of Technical Communications Skills",
              legacyPath: "/HTML/NotesComponentSem1/tc.html",
              notes: [
                { title: "Email Writing", fileId: "1raKPTkb9Sc72YnlIc0yAPMyg8tYM7QDR", type: "slides" },
                { title: "Technical Communication", fileId: "1nNCFSS5CKW4T5X_K4Axz5c159qZsvJOM", type: "slides" },
                { title: "Communication", fileId: "1dNgWKrZY2l8Z-Dklt3ZdJpua5mqGkuUU", type: "slides" },
                { title: "7cs of Effective Coms", fileId: "1TVMk73Xq1kBu-llzii9ODJzQWXC0XvU1", type: "pdf" },
                { title: "Technical Report", fileId: "1Sbn1zPmvMQ2rZW_mvp7O5MuhoXNcwiz_", type: "pdf" },
                { title: "Writing Email", fileId: "1S6OLyMSqcdhrrIweN1xZq2_gxpH6MSMe", type: "pdf" },
                { title: "Manuals", fileId: "1PzzIuBsbk_IVN4f9X6V3j_TWOKZhvZS4", type: "slides" },
                { title: "Useful Email Phrases", fileId: "1PQ11Hbg_LCvo2Tka4mxc8dVsY7fVNcwi", type: "pdf" },
                { title: "Email Etiquettes", fileId: "1JG-8fmBSqGrP0JzzAKEL5z-E73SF34n6", type: "pdf" },
                { title: "Technical Report", fileId: "19MGzlG0v9r49kHeib9zXXe66qxkYHKcf", type: "pdf" },
                { title: "Technical Communication Reference Book", fileId: "1-jvMLlEW1pOf_al-xYkO8PpBT9y-Ry2l", type: "pdf" },
              ],
            },
            {
              slug: "digital-electronics",
              title: "Digital Electronics",
              legacyPath: "/HTML/NotesComponentSem1/de.html",
              notes: [
                { title: "DF UNI1", fileId: "10CmeIy4LO5ne4LT16ootb_N2bJOjssYK", type: "pdf" },
                { title: "Unit 1", fileId: "1LWQSgBStY_928LEAxSLS0kO_tbgvNlVh", type: "slides" },
                { title: "Unit 2", fileId: "1LpftDV0_3HqGX1Nm6OU5wu-74oie8QOw", type: "slides" },
                { title: "Unit 3", fileId: "1Lp0kH1nLEfQWHYqfFgTdtVFoNpMwQEfG", type: "slides" },
                { title: "K MAP examples", fileId: "1MJsN2EafVvbsyjX3P0SclhgK39v0BhNJ", type: "pdf" },
                { title: "K MAP", fileId: "1MJRFzQSbbeDxSQkYBVmng7p6G8DMtop3", type: "slides" },
                { title: "Boolean Algebra", fileId: "1LtZqE3NS842wviMk3v7rWd5Nv_H7qjLc", type: "slides" },
              ],
            },
            {
              slug: "mathematics",
              title: "Foundational Mathematics (Linear Algebra and Calculus)",
              legacyPath: "/HTML/NotesComponentSem1/maths.html",
              notes: [
                { title: "Matrix Part 1", fileId: "1R7gd_O77hQbVLQZ4PEAjMkQKVMinKo0a", type: "pdf" },
                { title: "Matrix Part 2", fileId: "1ijE2XOJ2nKNWJZKN2VMbnjGpH58RKFCt", type: "pdf" },
                { title: "Matrix Part 3", fileId: "1eqsVt2lx9lxFbtLsvXbH1c6Wvpd-DCp7", type: "pdf" },
                { title: "Calculus and Integration part 1", fileId: "109LHDYbPburbtH1Usd5rNg6o2CZzPAkG", type: "pdf" },
                { title: "Calculus and Integration Part 2", fileId: "188QJQpWp8-le1vBgmNTyAIg740Y9WzPj", type: "pdf" },
                { title: "Calculus and Integration Part 3", fileId: "1veEXqPeG4Eww0xeLz5kUE7gbpxNyrLVD", type: "pdf" },
              ],
            },
            {
              slug: "environmental-studies",
              title: "Environmental Studies",
              legacyPath: "/HTML/NotesComponentSem1/es.html",
              notes: [
                { title: "Natural Resources Types", fileId: "1Hq5FvjEXung0jvqCSwPxPzJjD34vCsPX", type: "slides" },
                { title: "Concept of Ecosystem", fileId: "1HpANSyyx3znRckhJQE7AwtN-dSD87jwc", type: "slides" },
                { title: "Natural Resources", fileId: "1HlCEPPWu-9IvqdzUZZZJI1HYObtYDfSY", type: "slides" },
                { title: "Natural Resources 2", fileId: "1HfvloN8xoYWPSAnzNiAoUbWRBtdGQ9F6", type: "slides" },
                { title: "Biodiversity and Conservation", fileId: "1HfCoP1SKyXqN5JTzcu0e849YkeqL4yYP", type: "slides" },
                { title: "Introduction", fileId: "1HeUVC4lbKpGpqp1aaqIojT_Cgbyy91-1", type: "slides" },
                { title: "Hotspots", fileId: "1HdSP39YDsvSzjmpHNwTP91Hbje7g1PnS", type: "slides" },
              ],
            },
            {
              slug: "coi",
              title: "Constitution of India",
              legacyPath: "/HTML/NotesComponentSem1/coi.html",
              notes: [
                { title: "Nature of Constitution", fileId: "1NqqBwSq3CDoraf-sKAZSbmqVgMS76KEf", type: "slides" },
                { title: "Panchayat and Societies", fileId: "1Nlzi0UcFBoq2_mrGp66x1Qd0-qKbzNzK", type: "slides" },
                { title: "Parliament", fileId: "1NjA7pJ2lZnfk8jLjmZ0kzhc8jyvvaW1k", type: "slides" },
                { title: "President", fileId: "1NitCRfJtgJ7AIs3Wv4O9AKPNB1Hxsq27", type: "slides" },
                { title: "Preamble", fileId: "1Ngjfdgqmmx2pP-QacuiXehqN1Tf4CqbJ", type: "slides" },
                { title: "State Exeutie", fileId: "1NeA-uQNkxiN6Y6QLlUpR40rQ8oF5lwsV", type: "slides" },
                { title: "Article 23-24", fileId: "1NbjBbFAvYrcVq0KhYtrNdTa2VzHGdhpN", type: "slides" },
                { title: "Salient Features", fileId: "1NULGBC2Ej0ukRTZ2Z6IH-5vs4YFXwdfG", type: "slides" },
                { title: "State Judiciary", fileId: "1NRQowvLiyHkvLKe0kQKvFCpSg0RKNIsX", type: "slides" },
                { title: "Article 15", fileId: "1NOm1dPgHtYGn17NQR_YSCislVhxBqEOD", type: "slides" },
                { title: "Article 19", fileId: "1NNRTi_v0MgvNouPOvnxAbF8aJcnwu-Ul", type: "slides" },
                { title: "Article 16", fileId: "1NKX8nlXmqbBGAhX1j-s5EuEnmRpJknsb", type: "slides" },
                { title: "Article 17-18", fileId: "1NIXk5VpvJP5xakpkAX2WB8KVDrcYUATc", type: "slides" },
                { title: "Article 20", fileId: "1NFhgPsH-xDnSrwqaUViRBr9Br82io3dP", type: "slides" },
                { title: "Article 21", fileId: "1NDYbV5fr-LvF2-kFMq7XWOLWF2ULKZzW", type: "slides" },
                { title: "Article 22", fileId: "1N8d981cCIrQakWadsWwEX0-aaLMyzlrx", type: "slides" },
                { title: "Article 25-28", fileId: "1My49Jm_mTYfgmUhYbPbcJusG6ix0qu-7", type: "slides" },
                { title: "Article 29-30", fileId: "1MqAHtr4G7gR7F9aDdK5PkVanTOl0ZdL8", type: "slides" },
                { title: "Council of Minister", fileId: "1Mp8pIEnFM6VY2eERJBY1YRafKFR-x66A", type: "slides" },
                { title: "Union Judiciary", fileId: "1MhsbgFMZIjSmVjkc5qFlU-R7Ba9t6PzD", type: "slides" },
                { title: "Historical Background of COI", fileId: "1Mh1lradk_ZNeyIUamSjrQrIj8-6zaiD8", type: "slides" },
              ],
            },
          ],
        },
        {
          slug: "sem-2",
          title: "Semester 2",
          legacyPath: "/HTML/fysem2.html",
          subjects: [
            {
              slug: "cpp",
              title: "Programming with C and C++",
              legacyPath: "/HTML/NotesComponentSem2/cpp.html",
              notes: [
                { title: "Lec 1 Introduction to C and C++", fileId: "1OW1hyuaCYxkDXJal7CvGIqveym3rbGvT", type: "slides" },
                { title: "Lec 2 C Flow Controller", fileId: "1OFbL4NTz_xsCkgP72Lq2-7BzmjMuTfS1", type: "slides" },
                { title: "Lec 3 Function", fileId: "10xKi2QcmwV7gyI1LYXz6x8SYVa2fzlUc", type: "slides" },
                { title: "Lec 4 Array", fileId: "1R12dBRFRrnIscmsIdr-FzXAwHd8ATQuA", type: "slides" },
                { title: "Lec 5 Pounters Structure Unions", fileId: "1JgEeXtIqUnfnAxXuZl_JnfX12iUmAfRg", type: "slides" },
                { title: "Lec 7 File Handling", fileId: "1SMMvy_8YMps1y9qcEzK1OVHxGCnitGLu", type: "slides" },
                { title: "Lec 8 Oops Class and Objects", fileId: "1HX0N7L5Rc2AafVoAYnwloc7if93YdFyA", type: "slides" },
                { title: "Lec 9 OOPs", fileId: "1ugRGUWY-lRRk-rK26NnGNUfgWSln1A2g", type: "slides" },
                { title: "Assignment 1", fileId: "1ZNdDFnL-rs2gTlQzagLxYSUyaCAizNhi", type: "pdf" },
                { title: "Assignment 2", fileId: "1xjy6ChZsCCuuX5MsUDCcbSuPE94kL0GU", type: "pdf" },
                { title: "Assignment 3", fileId: "1ma_HsS7A0RhvGX9C_1rP62FkV3a8_Hkm", type: "pdf" },
                { title: "Assignment 4", fileId: "169mXBe6m6Z-fp8vlNdX_TLKz9tWv-CpE", type: "pdf" },
                { title: "Assignment 5", fileId: "1q97iNKBnyzc5X_RqkCIbDt29zWudxQbs", type: "pdf" },
                { title: "Assignment 6", fileId: "1BwmHq42BFx2YqI3d8zrsM-7UOuXgSkgb", type: "pdf" },
                { title: "C Reference Book", fileId: "1arU_bWmCJkGJLthqj3kTd3euO5Nnpn5o", type: "pdf" },
                { title: "C++ OOPs questions", fileId: "1Te9iIJM8dAvKk-n6vaSAqaRNlQ-AzDvX", type: "pdf" },
                { title: "C MCQs", fileId: "1_tXcyYNhFoCxZP23N37Cv0tbyiwpXbqI", type: "pdf" },
              ],
            },
            {
              slug: "dbms",
              title: "Database Management Systems",
              legacyPath: "/HTML/NotesComponentSem2/dbms.html",
              notes: [
                { title: "Lec 1", fileId: "1XSDJO1L92vXsiPSq3jgpVA2WikDcCf1e", type: "slides" },
                { title: "Lec 2", fileId: "1XNfFgeCe7i1f-Fsg1MZMcbPX6iLen43Z", type: "slides" },
                { title: "Lec 3", fileId: "1XG-BN_ZHVBjWF_nGylRXHNNf1eZdvmIj", type: "slides" },
                { title: "Lec 4", fileId: "1XbD1bbuPS9IWiMqffsAz8r2ragtX8kl6", type: "slides" },
                { title: "Lec 5", fileId: "1XXb-2VUZ7HP92D4mM8bBgq9_Ihsg2iu1", type: "slides" },
                { title: "Lec 6", fileId: "1X319rct9ql9WoAJnKoJq359y660VSIh4", type: "slides" },
                { title: "Lec 7", fileId: "h1X2jBtM0kSAB6Jy8c1hfURvwH3pLp3BQv", type: "slides" },
                { title: "Lec 8", fileId: "1gGP_0G3fCtwm8iyKyr0rZmuDv0WThYXd", type: "slides" },
                { title: "Lec 9", fileId: "1gNsaj4izsk1VpDYHm_EprPMXBT7ccwUb", type: "pdf" },
                { title: "Lec 10", fileId: "1gS2amghNRWmyDD0C_sB-bZmWmJgJnvBP", type: "pdf" },
                { title: "Lec 11", fileId: "1g2Fx1v2qTqJX2Lz7dXsMVRU83i73cS6y", type: "pdf" },
              ],
            },
            {
              slug: "coa",
              title: "Computer Organization and Architecture",
              legacyPath: "/HTML/NotesComponentSem2/coa.html",
              notes: [
                { title: "Unit 1 Logic Microoperations", fileId: "1mf5Wj0bpVQxOkKTF-5wqeyGwW3kCvSzb", type: "slides" },
                { title: "Unit 1 History of Computers", fileId: "1bvITlVL7DB0IS7K6SH-pot4BzYP_63vR", type: "slides" },
                { title: "Unit 1 Arithmetic Logic Shift Unit", fileId: "1WIrDEF5cDKI3MRFG6bF8umjQ0rwLwl76", type: "slides" },
                { title: "Unit 1 Shift MicroOperations", fileId: "1SokwNzTF6rYJBJOqeNeHJUkyvjppcX4m", type: "slides" },
                { title: "Unit 1 NUmber System", fileId: "1QAk7_-AAHnWtPLkoFM6aFETi06pMt7PT", type: "slides" },
                { title: "Unit 1 Booths ALgorithm", fileId: "1GAGkj1M3mi68SI4GdRnUk6r1AmR_N2R7", type: "slides" },
                { title: "Unit 1 Floation Points Ops", fileId: "1CR4OWEp6KZ_9ZXLL-sIVb0dEkSgaSl2E", type: "slides" },
                { title: "Unit 1 Stored Programs", fileId: "1BNkNv-aHIyfxOPM9WfHtSFdVkztVtqtP", type: "slides" },
                { title: "Unit 1 Arithmetic MicroOPerations", fileId: "1Ah7CvT2a0bNSI-K57uw16BvQ_mVzSu8R", type: "slides" },
                { title: "Unit 1 Logic Gates", fileId: "18JUxOtYg3hW6hK7Y0y5X3R_A8LcGaE9c", type: "slides" },
                { title: "Unit 1 Addition and Substraction using Complements", fileId: "13OT8_9DfGnCQqB24Rew0e8TA4FC1l26R", type: "slides" },
                { title: "Unit 2 Instructions Code", fileId: "1jOPG2YDrIRqT9hCBi4CBLlfkaZhBu68H", type: "slides" },
                { title: "Unit 2 Common Bus System", fileId: "1aa-MBJYhCjJfh7ZX2PbFxCLJdrmL-kRG", type: "slides" },
                { title: "Unit 2 Timing and Control", fileId: "1Wu0rifzzADWE_SnxFpeaLussKYe0V1UD", type: "slides" },
                { title: "Unit 2 Instruction Format", fileId: "1VgXMYH7IuyZ2rjYtEDx49aBKXLMbRNL1", type: "slides" },
                { title: "Unit 2 Instruction Cycle", fileId: "1Sape-4PHeC-3jwxaYEbYyyBurHsIn4mR", type: "slides" },
                { title: "Unit 2 Interrupt Cycle", fileId: "1SN2-QWBrruKb8Ei0Zc6oYXMPIsyWzbkh", type: "slides" },
                { title: "Unit 2 Input-Output Instructions", fileId: "1Db0Mju1-FSbN6DDs4LUJkbz_IK45ypBF", type: "slides" },
                { title: "Unit 2 Computer Registers", fileId: "13XGqCdnGkheK-C1PhIfd_Z3tNYPEckKF", type: "slides" },
                { title: "Unit 3 Arithmetic Pipeline", fileId: "1gu9Hv-TIlMnzAyIX2ckWLTW3aMkp_p9J", type: "slides" },
                { title: "Unit 3 Pipelining", fileId: "1gYxAZPb2muM4muMgbIj4fi6xywutvk0F", type: "slides" },
                { title: "Unit 3 Array and Vector Processing", fileId: "1bHKdUAEFKkoF6-YZXvoTFKBCYtOZrexC", type: "slides" },
                { title: "Unit 3 Flyn's Taxonomy", fileId: "1VAf2dVD3bhZArG7IT-f1SKHRcavt7Cvs", type: "slides" },
                { title: "Unit 3 I/O Organzation", fileId: "1OklbeENUc0cSH9D9mpV-rhgKPqdsGEF5", type: "slides" },
                { title: "Unit 3 Instruction Pipleline", fileId: "1GUVm5p8o7laeS3Te4OW8O5BIrFT5Eld_", type: "slides" },
              ],
            },
            {
              slug: "discrete-mathematics",
              title: "Discrete Mathematical Structures",
              legacyPath: "/HTML/NotesComponentSem2/dmaths.html",
              notes: [
                {
                  title: "Unit 1 and 2 Propositions and Group Theory",
                  fileId: "1JCi2C0ZB3oTurVJpSfmYWk2Ciq3R_Hsp",
                  type: "pdf",
                },
                { title: "Unit 3 Graph Theory", fileId: "1JDeNJhci3u_nZBTcNdou9M-7nhoS6wb5", type: "pdf" },
              ],
            },
            {
              slug: "aec",
              title: "Mastering Technical Communication skills",
              legacyPath: "/HTML/NotesComponentSem2/aec.html",
              notes: [
                { title: "Technical Presentation", fileId: "1zPEAuogVwSzkU-f7nvj0_Bu14D7SCzjb", type: "slides" },
                { title: "Critical Thinking and Writing Skills", fileId: "1dqdOlX1R89vpSj_x4IZ_2zO0fK-hzke0", type: "pdf" },
                { title: "Mastering Technical Communication", fileId: "1YHlevoxLf-CKOg9z7zRyMvR82O0CpAIC", type: "pdf" },
                { title: "History of English", fileId: "1YGrkvtGZcVDo9KT3TggXiyp25Y5NI6-K", type: "slides" },
                { title: "Comprehending Reading Skills", fileId: "1YvMQxVRqWv_cHeIXTjCP5Tm5VX_rnEcR", type: "pdf" },
              ],
            },
            {
              slug: "disaster-management",
              title: "Disaster Management",
              legacyPath: "/HTML/NotesComponentSem2/dm.html",
              notes: [
                { title: "Tropical Cyclones", fileId: "1ybW21fcpkYVgJ-AK67OykhlkhKW5OOeX", type: "pdf" },
                { title: "Industrial Disasters", fileId: "1yTP9IRZMOSDScbtnl_M3ALb-8Ld2fZJG", type: "pdf" },
                { title: "Disaster Management", fileId: "1tkL6A3k4bW-c7yKQf5vBft9iOlgixh9z", type: "slides" },
                { title: "Forest Fires", fileId: "1ruGXf0R20K-FZylzKS5S1BJVxZ8h6mmt", type: "pdf" },
                { title: "Risk and Harazd Analysis", fileId: "1cMqBoVIxx7CbP5FYR3lYeYwQgTLfpa3h", type: "pdf" },
                { title: "Disaster Management Cycle", fileId: "1bryA-QPFWARQWymsKw9oLgTH3Sfq4yjB", type: "slides" },
                { title: "EarthQuake , Tsunamis , DMP", fileId: "1PrRU9I4axRybvNjMA1hGUwFSXiohOWZ8", type: "pdf" },
                { title: "Droughts", fileId: "1NWfsltdPIsM95AyajpuM6fsmAVqZVDVP", type: "pdf" },
                {
                  title: "Mass Movement and Mass Wasting",
                  fileId: "1L6U3L8j7yY7H-23tW9w47D0CEikbR0s8",
                  type: "pdf",
                },
              ],
            },
            {
              slug: "eda",
              title: "Exploratory Data Analysis",
              legacyPath: "/HTML/NotesComponentSem2/eda.html",
              notes: [
                { title: "Unit 1 and 2", fileId: "1YJyUYUzcwhOdhmJc76WpmGMubwDat5Of", type: "pdf" },
                { title: "Unit 3 and 4", fileId: "1fj_5VWGgYzp0531j-2tmYIeD0j_ciVLr", type: "pdf" },
              ],
            },
            {
              slug: "cyber-law",
              title: "Cyber Law",
              legacyPath: "/HTML/NotesComponentSem2/cl.html",
              notes: [
                { title: "Cyber Law and Ethics", fileId: "1eNSYiQCsUwF4Ju1trf6zCM8_e-Z-fLYT", type: "slides" },
                { title: "Section 43 Cyber law", fileId: "1YFvEk-KcWQZ4uHZ0Mc2EHz2ZjYPXRQCH", type: "slides" },
                { title: "Cyber Law", fileId: "1YD77h8a22oEmbgvOj2U4pQ29XeSc_nBE", type: "slides" },
                { title: "HnadWrittenNotes MidSem", fileId: "1YCxhMeCz35g2CuPX5MaHh0kAs_QlWw5E", type: "pdf" },
              ],
            },
          ],
        },
      ],
    },
    {
      slug: "second-year",
      title: "Second Year",
      legacyPath: "/HTML/secondyear.html",
      semesters: [
        {
          slug: "sem-3",
          title: "Semester 3",
          legacyPath: "/HTML/sysem1.html",
          subjects: [
            {
              slug: "client-side-web-development",
              title: "Client Side Web Development",
              legacyPath: "/HTML/NotesComponents/cwhSY.html",
              notes: [
                { title: "HTML-Chapter_wise", fileId: "18oXeWBOnZv0v6IClUg2Ib5qX2wtTrapo", type: "pdf" },
                { title: "CSS-Chapter_wise", fileId: "18o_vPjW82zBScScPv2Nu2fLE2BxhJkhk", type: "pdf" },
                { title: "JS-Chapter_wise", fileId: "18t6knSI6JnOkiki8sqqU1Q7QQizl72re", type: "pdf" },
              ],
            },
            {
              slug: "dsa",
              title: "DSA",
              legacyPath: "/HTML/NotesComponents/dsaSYsem1.html",
              notes: [
                { title: "DSA with C and C++ Textbook PDF", fileId: "1Yx4aNENiXEeJQgkNLCFqkQ8HttvBEdmh", type: "pdf" },
                { title: "DSA with C and C++ Mid Sem Answers", fileId: "1FxIE-gckYLPp5hlza-T4ScRW1OiWIyMi", type: "pdf" },
              ],
            },
            {
              slug: "it-skills-data-analysis",
              title: "IT Skills And Data Analysis",
              legacyPath: "/HTML/NotesComponents/itSY.html",
              notes: [
                { title: "Data Vizualisation", fileId: "1fl8ald25TPt3DXV8224jMzvQ_hvoDMTt", type: "pdf" },
                { title: "IT-skills", fileId: "1Y-FusfTgHYoEVoOqOPvyTDTkr_sBKA2R", type: "pdf" },
                { title: "Pandas", fileId: "1XydoPI2YkPEO2UFjWspgNcNIIMNUvJ1u", type: "pdf" },
              ],
            },
            {
              slug: "operating-systems",
              title: "Operating Systems",
              legacyPath: "/HTML/NotesComponents/osSYsem1.html",
              notes: [{ title: "OS Reference book", fileId: "1DUdlmL-UMTFEvnfV-sw0Aw4uIyltsAR9", type: "pdf" }],
            },
            {
              slug: "financial-accounting",
              title: "Introduction to Final Accounting",
              legacyPath: "/HTML/NotesComponents/faccountingSY.html",
              notes: [
                {
                  title: "Introduction to Financial Accounting",
                  fileId: "15ZrT2We56Qqx54GGUdTFTe2O2LCpUrq-",
                  type: "pdf",
                },
                { title: "Jounral and Subsidiary Book", fileId: "1G1RY2oOc61X16WVszccXUpHhCMRBBWbT", type: "pdf" },
                { title: "Jounral Entry with GST", fileId: "1GF-W8hROsIMvb5G7I6RIilpykskw4LjD", type: "pdf" },
                { title: "Financial Statemet Analysis", fileId: "1GCi75FxnIOj01wPaSqRF5dT4KzA6_iSI", type: "pdf" },
                { title: "Unit 2 Final Account", fileId: "1GEstR9-qTvKGeeKDzaQ_JjdfrdLdNMIU", type: "pdf" },
                { title: "Question bank", fileId: "1GAT0kioS16fZeu-6TCcIJtNtIbqD472S", type: "pdf" },
                { title: "HandWritten Notes", fileId: "1GF8VJURMthN4rWHXZzOpxD4CvfHTswpT", type: "pdf" },
              ],
            },
            {
              slug: "e-waste-management",
              title: "E-Waste Management",
              legacyPath: "/HTML/NotesComponents/emanagementSY.html",
              notes: [
                { title: "Lec 1", fileId: "1er9A6Ls7JP9RM9hZJI1rrf2UmeYo1Xot", type: "pdf" },
                { title: "Lec 2", fileId: "1eyUJOXEb8oPZuCrjhu-tjMMhaGziUMzN", type: "pdf" },
                { title: "Lec 3", fileId: "1nQvzWHCFD5lnPio5-MfU2ABQfDMnoeva", type: "pdf" },
                { title: "Lec 4", fileId: "1nBjMFJzjfaKPqpi0LUCEx5gndxcem_bQ", type: "pdf" },
                { title: "Lec 5", fileId: "1nNrIwgXOttn134EpUhoqlk7vzpZrk0cg", type: "pdf" },
                { title: "E-waste Rules", fileId: "1nMoiQwAxbt5PAJ-yIOwnEGazxToIhJ2f", type: "pdf" },
              ],
            },
            {
              slug: "aec",
              title: "AEC",
              legacyPath: "/HTML/NotesComponents/aec.html",
              notes: [
                { title: "English For Business Communication", fileId: "1cKY-4rgCWtKgeAK_0SH_z0WzWikEZduk", type: "pdf" },
                { title: "English for EnterPreneurship", fileId: "1c9lgu8Dca4uZSiwpaCYgf3tLyydnvy8z", type: "pdf" },
                { title: "Guide to both", fileId: "1c7RvRlZmsvS_7nsizWodItNL1hlaoQt8", type: "pdf" },
              ],
            },
          ],
        },
        {
          slug: "sem-4",
          title: "Semester 4",
          legacyPath: "/HTML/sysem2.html",
          subjects: [
            {
              slug: "career-skills",
              title: "Carrier Skills",
              legacyPath: "/HTML/NotesComponentsSem4/cSkills.html",
              notes: [
                { title: "Career Skills Handout", fileId: "1kC4Vz2ucsLv5p2UxOnEO0BNaQoLtG4id", type: "pdf" },
                { title: "Interview Skills", fileId: "1icn8fe1DdTPnTzlHhgZa8p5xQZe1xwjX", type: "pdf" },
                { title: "Adaptability, Critical Thinking", fileId: "1QRV7BAzqYUBvR9ZYu_lG3Tc-g0dN3a3c", type: "pdf" },
                { title: "Unit 1 Handout", fileId: "1QPBASv1UZpxkjRGzh1c0VDr0m2ZAA_7x", type: "pdf" },
              ],
            },
            {
              slug: "dcn",
              title: "DCN",
              legacyPath: "/HTML/NotesComponentsSem4/network.html",
              notes: [
                { title: "Connecting Devices", fileId: "1POUuASIWTJaQPlbXlx_Plg3J0SH1ABAY", type: "pdf" },
                { title: "Connecting Devices", fileId: "1PMoCcEXT9Pa9WqBS6kOkfkmlVveTjOEd", type: "slides" },
                { title: "Transmission Media", fileId: "1PKNwjeVf-o_Df_2U3t9cWQH5h6nomK11", type: "slides" },
                { title: "Data Communication and Networking", fileId: "1PI72jkxsJWPeALu-cgQgDurFmusMj5GO", type: "pdf" },
                { title: "DDL Protocol", fileId: "1PDxw8jrI0HdVbS-gEBKc4yhgMPaZkW-X", type: "slides" },
                { title: "IP Address", fileId: "1OmEaY2uPLUuu5Usq9PLRn3T8YnYj0Kl3", type: "slides" },
                { title: "LAN WAN MAN CAN", fileId: "1Om10sGHsNeIrrjq1-rkDt5FVIMMd16XU", type: "slides" },
                { title: "ipv6", fileId: "1OntSdviYCDr9ncUIdIkeNTNQSuvIg1Aq", type: "slides" },
                { title: "MAC", fileId: "1OkZBeUiruDraG2IyJSNIjyL5nFMgrAwS", type: "slides" },
                { title: "Nework Topology", fileId: "1OkLvGhxMaWZLCahQIB6D3WIPz6s7rss1", type: "slides" },
                { title: "Error Detecting", fileId: "1Ok-9b0wnSquOLpKO75kAlN6OvJB1e5jF", type: "slides" },
              ],
            },
            {
              slug: "carbon-neutrality",
              title: "Fundamentals of Carbon Neutrality",
              legacyPath: "/HTML/NotesComponentsSem4/dcn.html",
              notes: [
                { title: "Net Zero", fileId: "1cSxgs0_HYJrWxrD268mgEXjdUBoLxpxM", type: "pdf" },
                { title: "Carbon Footprint", fileId: "1cQIOFARonr6nF6OB4RfIS7dsJ9Nuo2-I", type: "pdf" },
                { title: "Carbon Basics", fileId: "1cLF-DaOifjiVB6nxiuyfn84iGU_QrN0m", type: "pdf" },
                { title: "Unit 2", fileId: "1OeRgDXk9s8cKLsEe0x1ZtwANs8-SOy8w", type: "slides" },
              ],
            },
            {
              slug: "php",
              title: "PHP",
              legacyPath: "/HTML/NotesComponentsSem4/php.html",
              notes: [{ title: "PHP Reference Book", fileId: "1N8xeBSxIKNNKWflwoHrCmhO1ha90bWxd", type: "pdf" }],
            },
            {
              slug: "java",
              title: "Introduction to JAVA",
              legacyPath: "/HTML/NotesComponentsSem4/java.html",
              notes: [{ title: "Java Reference Book", fileId: "1I_H3_WQ-cPa7xx6vqwgWqhZbUgpzhGYr", type: "pdf" }],
            },
            {
              slug: "software-engineering",
              title: "Software Engineering",
              legacyPath: "/HTML/NotesComponentsSem4/software.html",
              notes: [
                { title: "Introduction", fileId: "1Mxe6KA7IaJxr4VboQOewwVhW9Wc7MCLP", type: "slides" },
                { title: "XP and Scrum", fileId: "1Mf5GXg_8XynZYnB4NsSw5UV7euQCi6WV", type: "slides" },
                { title: "Agile Model", fileId: "1MZuA9Bchqp3wBLns89U60OTNcboWy0pH", type: "slides" },
                { title: "Software Process Model", fileId: "1MQRgDaZD7ariVz6_Jv6V0DeImH2mGMZX", type: "slides" },
                { title: "Software Process", fileId: "1MIqHi3FqtHc9QA1wMTzDlyTSSC0wkacO", type: "slides" },
                { title: "Requirement Engineering", fileId: "1UCXq0XrHbInZ2UDRxPmcvP2gsjpjOwzP", type: "slides" },
                { title: "Project Management Concept", fileId: "1U9Jw-jRV6tMecQkKo9HHlGmwAfGiA9uO", type: "slides" },
                { title: "Sofrware Metrices", fileId: "1UCgYR89Nq3Y2fEBTT-h5EabVGndCWHQn", type: "slides" },
                { title: "Cocomo Model", fileId: "1OpEdAdrRqrH_9yyHwchNQV8PBaYMm15z", type: "slides" },
                { title: "Quality", fileId: "1Oqt2lMq2c1pLim4NWCIgvk5f2m5eMrrG", type: "slides" },
                { title: "Software Texting", fileId: "1OqpMwSKxNAqvIK0cekgml-UvJImq6pok", type: "slides" },
                { title: "Risk Management", fileId: "1Oq4pJozhdZmb1dqAUZYRveBlrXX6u7AM", type: "slides" },
              ],
            },
            {
              slug: "english-digital-virtual-communication",
              title: "AEC",
              legacyPath: "/HTML/NotesComponentsSem4/edvc.html",
              notes: [
                {
                  title: "Unit 1 Multimedia and Content Dev",
                  fileId: "1bnnFm5NalKSTuDKAFzbu18O7_OyUJigI",
                  type: "pdf",
                },
                {
                  title: "UNit 1 SEO Basics and content optimization",
                  fileId: "1U7oxX6HDwX0oIe00UXLdi3QnmOZezqK8",
                  type: "pdf",
                },
                { title: "Unit 1 English for Digital Coms", fileId: "1U798XDdJdhrMd3olpkJVcgN7mYnCY4ta", type: "pdf" },
                {
                  title: "Unit 1 Principles of effective online writing",
                  fileId: "1U-_AJjb7SF7-NoaSZqMmddblSfK2R2_M",
                  type: "pdf",
                },
                { title: "Unit 2 Best Practices for meeting", fileId: "1iM69dspkfOnMGu-OS6xiPYrTaBxr3oji", type: "pdf" },
                {
                  title: "UNit 2 Tools and Tech for Virtual Coms",
                  fileId: "1iHcHXU8Kjh6Qo3zgKo1-vHZFf5USiR9-",
                  type: "pdf",
                },
              ],
            },
          ],
        },
      ],
    },
    {
      slug: "third-year",
      title: "Third Year",
      legacyPath: "/HTML/thirdyear.html",
      semesters: [
        {
          slug: "sem-5",
          title: "Semester 5",
          legacyPath: "/HTML/tysem1.html",
          subjects: [
            {
              slug: "software-engineering-2",
              title: "Software Engineering-2",
              notes: [],
            },
            {
              slug: "software-testing",
              title: "Software Testing",
              notes: [],
            },
            {
              slug: "mobile-application-development",
              title: "Mobile Application Development",
              notes: [],
            },
            {
              slug: "web-application-development",
              title: "Web Application Development",
              notes: [],
            },
            {
              slug: "algorithm-design-and-analysis",
              title: "Algorithm Design and Analysis",
              notes: [],
            },
            {
              slug: "application-frameworks-in-java",
              title: "Application Frameworks in Java",
              notes: [],
            },
            {
              slug: "artificial-intelligence",
              title: "Artificial Intelligence",
              notes: [],
            },
          ],
        },
        {
          slug: "sem-6",
          title: "Semester 6",
          legacyPath: "/HTML/tysem2.html",
          subjects: [],
        },
      ],
    },
  ],
};
